export const data = [
    {
        id: 1,
        productName: "第一件商品",
        imgUrl: "women.png",
        price: "$200",
        sale: "$150",
        star: "5.0",
        sold: "1",
    },
    {
        id: 2,
        productName: "第二件商品",
        imgUrl: "man.png",
        price: "$300",
        sale: "$250",
        star: "4.5",
        sold: "100",
    },
    {
        id: 3,
        productName: "第三件商品",
        imgUrl: "kid.png",
        price: "$400",
        sale: "$350",
        star: "3.0",
        sold: "500+",
    },
    {
        id: 4,
        productName: "第四件商品",
        imgUrl: "women2.jpg",
        price: "$500",
        // sale: "$350",
        star: "4.2",
        sold: "200+",
    },
    {
        id: 5,
        productName: "第五件商品",
        imgUrl: "man2.jpg",
        price: "$200",
        // sale: "$150",
        star: "4.0",
        sold: "150+",
    },

    {
        id: 6,
        productName: "第六件商品",
        imgUrl: "kid2.jpg",
        price: "$600",
        // sale: "$450",
        star: "3.8",
        sold: "500+",
    },
    {
        id: 7,
        productName: "第七件商品",
        imgUrl: "women3.jpg",
        price: "$1200",
        sale: "$1000",
        star: "5.0",
        sold: "1000+",
    },
    {
        id: 8,
        productName: "第八件商品",
        imgUrl: "women4.jpg",
        price: "$500",
        sale: "$250",
        star: "3.0",
        sold: "100+",
    },
    {
        id: 9,
        productName: "第九件商品",
        imgUrl: "man3.jpg",
        price: "$400",
        sale: "$350",
        star: "4.7",
        sold: "200+",
    },
    {
        id: 10,
        productName: "第十件商品",
        imgUrl: "kid3.jpg",
        price: "$400",
        sale: "$350",
        star: "3.0",
        sold: "10",
    },
];
